wharfix/wharfix

- src/main.rs
This was a regression introduced with #17
path-canonicalization is now done in a subroutine, so we shouldn't try to move up a directory-level before serving manifest.json. This causes us to end up in the root of `/nix/store`, i.e. `/nix/store/manifest.json` - whoops.
The reason this didn't show in my local tests of #17 is... my local docker image cache. Docker doesn't want to even try to pull: `localhost:8088/sl@sha256:05383ff1d78337b9014cae19195d1f6c2c1d0d4a2937de18893fd2f919c90941` because it recons that it already has that.
Note to self: use Curl more for testing -- or if using the docker cli, remember to system prune before the test.
> manifest/cache: don't jump to 'parent directory' anymore, path-canonicalization is done elsewhere

- src/main.rs
Reverts wharfix/wharfix#18
#18 has to be reverted, because I was stupid.
We after all _need_ to traverse to "parent directory", because since #11 we are now caching the manifest-file as blob, and the confusing part is that `parent()` here just means "dirname", i.e. we need the dirname of the resolved cache-path like:  `/nix/store/ihzwrk2k6w63yx6x8s75njv8cf6r7l5y-toolbox-servable/manifest.json` -> `/nix/store/ihzwrk2k6w63yx6x8s75njv8cf6r7l5y-toolbox-servable`, which we then later append `manifest.json` to in line 633.
The blob-cache dir on nix-build-p03 needed to be cleared in order to discover this mistake.
> Revert "manifest/cache: don't jump to 'parent directory' anymore, path-canonicalization is done elsewhere"

- Cargo.lock
- Cargo.nix
- Cargo.toml
wharfix fails on repo clone with `invalid version 0 on git_proxy_options`. As a temporary solution, let's downgrade git2 and pin it, until the issue is (hopefully) resolved.
ref rust-lang/git2-rs#746
> git2: pin to 0.13.21 until rust-lang/git2-rs#746 is fixed

- Cargo.lock
- Cargo.nix
- Cargo.toml
- nix/sources.json
Transitively bumps libgit2-sys to support libgit2 >= 1.3.0
> git2: 0.13.21 -> 0.13.25

- drv.nix
Handles difference in layer naming when `fromImage` is used in a docker spec. The check is not very robust, but should do for now.
> drv.nix: handle different layer naming when `fromImage` is used in spec

- Cargo.lock
- Cargo.nix
- Cargo.toml
- flake.lock
- src/main.rs
First part of cleaning out dependabot alerts: Pin only major versions in Cargo.toml. Also: cargo update + crate2nix update + flake update.
Next step: Major upgrade a bunch of dependencies in separate PRs.
> Pin only major versions

- Cargo.lock
- Cargo.nix
- Cargo.toml
- src/errors.rs
- src/main.rs
We've previously been seing 408 Request Timeout at our CI suspecting the culprit being non-bucketed blobcaching with too many files in the blobcache dir.
Randomly, while debugging something else, I discovered however: actix worker threads hanging in nix-eval, causing incoming http-requests to not get served.
This change - using async-process - causing worker threads to yield while the external process (nix-eval/nix-build) is running. This frees the worker threads to handling more incoming requests.
I've ran performance tests on my laptop with 10 concurrent GET manifest requests for 10 seconds (no caching). Without this change ~40% of the requests timeout after 10 seconds. WITH this change: all requests succeeds with an average response time of 3.5 seconds.
Note that Wharfix DOESN'T …
> blocking exec -> async exec

- flake.lock
- flake.nix
The example choo-choos correctly. crane is an almost arbitrary choice as replacement, but hopefully I've kept the outside facing API intact.
I see no dependencies upon mysql in the final binary, but there wasn't one before either, so I assume it's a pure rust library without ffi deps.
> 22.11 compat (bumps, crane, ...)

- src/errors.rs
Example debug output (response from GET)
```
{
"errors": [
{
"code": "MANIFEST_UNKNOWN",
"details": "debug help",
"message": "git2 error: GenericError. Message: Failed to open SSH channel: Error waiting on socket"
}
]
}
```
> Emit git2 errors

- flake.lock
- flake.nix
Signed-off-by: Christina Sørensen <christina@cafkafk.com>
> build(flake): update nixpkgs lock `23.05 -> 23.11`, bump inputs

- src/main.rs
Rev-parse of local ref (obviously) does not give expected result after git-fetch, since
only FETCH_HEAD and tracking branches are updated.
Instead of just a fallback, _always_ use /refs/remotes/origin/<ref> . Since we control the initial clone to temp, we can safely hardcode the name of the remote.
fixes #89
> Local rev-parse fails for updated remote refs

- Cargo.lock
- Cargo.toml
This is to fix CVE-2024-24577, I haven't ensured whether or not this affects
wharfix in any serious way, but there is no reason to keep an insecure version
around.
Signed-off-by: Christina Sørensen <christina@cafkafk.com>
> fix: update libgit2 to 1.7.2

- Cargo.toml
- src/main.rs
- **refactor(gcroots): make `ADD_NIX_GCROOTS` safe**
- **refactor(indexfile): make indexfile safe**
- **refactor(servetype): make servetype safe**
- **refactor(targetdir): make targetdir safe**
- **refactor(blobcachedir): make blobcachedir safe**
- **refactor(substituters): make substituters safe**
- **refactor(sshprivatekey): make sshprivatekey safe**
> refactor: remove setting and getting statics unsafely with OnceLock

- flake.nix
- src/main.rs
- tests/ref.nix
- tests/res/new-index.nix
- tests/res/old-index.nix
This prevents local branches from lingering in /tmp and hence forces resolve of _remote_ refs (only) using the current revparse logic.
fixes #89 #93
Drafting because: This time, it could be nice with some test cases to go along with the PR :).
> Init-bare in /tmp instead of cloning

- Cargo.lock
- Cargo.toml
- src/errors.rs
- src/main.rs
NOTE: This is stacked on #100.
- **build(cargo): add `log` and `pretty_env_log` to dependencies**
- **feat: add "idiomatic" rust logging**
This introduces the `oldlog` feature to preserve the old logging style, but
default to using the more *idiomatic* logging macros with `pretty_env_logger`
(which should be easy to replace with something else).
This is partially to make the output more readable, and I was informed that the
logging format is kinda an idea that never took off.
> feat: idiomatic logging

- .github/workflows/check.yml
Change the default Github CI action to flake check. The check implies a build of wharfix, so I hope it's ok we don't have an explicit nix-build step? Let me know what you think.
> ci: build -> flake check

- flake.nix
- justfile
- tests/arguments.nix
- tests/res/new-index.nix
This adds testing for:
- `--repo`
- `--path`
- `--address`
- `--port`
- `--blob-cache-dir`
- `--target`
- `--index-file-path`
- `--add-nix-gcroots`
> test(arguments): adds tests for most wharfix arguments

- src/cli.rs
- src/main.rs
Drop mutual exclusive flag checks for --dbconnfile, since clap 4 apparently actually have runtime checks for whether an arg constraint is spelled correctly.
I prefer (subjectively) having --dbconnfile not appear as a possible arg when wharfix is not compiled with "mysql"-support, over having correct mutual exclusion checks.
> fix: clap upgrade broke mysql feature

- src/cli.rs
turns out we _have_ to do this the ugly way (as decribed https://github.com/wharfix/wharfix/pull/109#issuecomment-2012445332), otherwise suddenly path/repo is required even when using "dbconnfile".
it's not _that_ bad when doing it this way, unless all the feature-guard macros hurt eyes too much.
sorry for not testing this earlier, I really should write an integration test for the mysql feature.
> fixup: required arguments when using the mysql feature

- flake.lock
- flake.nix
crane complains that the minimum version required is 24.05, and we want to bump it anyway.
> nixpkgs: 24.05

- .github/workflows/build.yml
This tests all feature combinations we currently support (it's not fancy enough to figure out features itself). It is however fancy enough to cache dependency artifacts from cargo.
Also, this is not on the self-hosted runner because that requires changing that runner to add cargo dependencies, and also because it only seems to be able to run a single check at a time. 
By using github runners instead, we get waste their cycles for free, and we get to do so in parallel :D 
Closes: #112
> ci: build all features

- Cargo.toml
Currently, several versions are locked on `0`. Because of how semver
works, this means that of these dependencies are allow to freely be
upgraded with breaking changes. Essentially, it's equivalent to setting
`*`, only as long as it doesn't go to a "one dot" release.
Most of the cargo ecosystem is pre one dot, and will be so forever, so
this is extremely brittle.
wharfix v0.1.0 (/home/ces/org/src/dbc/wharfix)
├── actix-rt v2.10.0
├── actix-web v4.9.0
├── async-process v1.8.1
├── async-stream v0.3.5
├── clap v4.4.18
├── dbc-rust-modules v0.1.0 (https://github.com/dbcdk/rust-modules?branch=main#ab38efd1)
├── erased-serde v0.4.5
├── futures v0.3.30
├── get_chunk v1.2.2
├── git2 v0.19.0
├── lazy_static v1.5.0
├── linereader v0.4.0
├── log v0.4.22
├── pretty_env_logger v0.5.0
├── regex v1.10.6 …
> fix dependencies to major versions

- Cargo.lock
- Cargo.toml
- flake.lock
- flake.nix
In order to perform this upgrade succesfully, it is nescesarry to update
all dependencies, including both cargo and flake, and bumping the rustc
MSRV to 1.81. This will also require moving the testing commit, which
will be done in a follow up.
Refs: https://github.com/DBCDK/faythe/security/dependabot/25
Signed-off-by: Christina Sørensen <christina@cafkafk.com>
> fix: `inda` insecure, and all it takes to deal with that (part 1)
